development:
  adapter: postgresql
  encoding: unicode
  database: login_development
  host: localhost
  pool: 5
  username: postgres
  password: enbake

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: pguser
  password: enbake